service: fullpath-parser
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  parse:
    handler: parser/parser.handler
    events:
      - httpApi:
          path: /parse
          method: post
